### ISSUE TITLE
Bug | AutoSave is not actually  autosaving

### ISSUE THREAD

**Issue by shreenarayan123** [aadeshkulkarni/figuringout#226]
### Where ?

- User visits the Publish page
- User creating new story

 ### What ?

- Auto save does not display saved content

**Procedure to Generate the situation**

1. Click on write icon on Navbar
2. Start a new story write title and desc
3. After 5-10 seconds refresh the page wait for 5-10 sec
4. Title and Desc are still empty not displaying the earlier content

**Comment by aadeshkulkarni** [comment]
I can confirm this. write-draft object in localstorage is empty.

**Comment by Vishnu-dholu** [comment]
I have fixed it.  [Here](https://github.com/aadeshkulkarni/figuringout/commit/c836da056265c7c4e4ad1adc36f2f6019ecfeab1)

**Comment by shreenarayan123** [comment]
@Vishnu-dholu But its still not displaying on screen after refresh

**Comment by Vishnu-dholu** [comment]
> @Vishnu-dholu But its still not displaying on screen after refresh

because you are instantly reloading the page after updating the content.
The autoSaveHandler is updating or autosaving the data in interval of 15 sec.
![snippet](https://github.com/aadeshkulkarni/figuringout/assets/75061058/89493c4d-219a-490f-a51e-255f9f8b94ed)

**Comment by aadeshkulkarni** [comment]
1. The localStorage is being set with an empty object during auto-save, hence, the auto-save breaks.
2. We need to reduce the interval to 5 seconds.

![Screenshot 2024-07-03 at 8 59 57 PM](https://github.com/aadeshkulkarni/figuringout/assets/67855887/2f8f4fd5-ce51-4757-a961-2eaa16a33554)

**Comment by AliYar-Khan** [comment]
@aadeshkulkarni I would like to work on this issue
I will reduce the interval for autoSave to 5 sec and also make sure that the drafts are being saved to local storage by debugging and solving the issue
